# This file lists the dependencies needed to build and test all of e-antic.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: e-antic-build
channels:
  - conda-forge
  - defaults
dependencies:
  - arb
  - antic
  - automake
  - benchmark
  - boost-cpp
  - coreutils
  - cxx-compiler
  - libflint
  - gmp
  - libtool
  # valgrind is only needed for make check-valgrind
  # - valgrind
