# Pins from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml
# so our packages is compatible with the choices made by conda-forge.
arb:
  - '2.20'
boost_cpp:
  - '1.74.0'
gmp:
  - '6'
libflint:
  - '2.8'
